workflows:
  ios-testflight:
    name: HemaTrack iOS TestFlight Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter create .
      - flutter pub get
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - mci.eyelashes@gmail.com
