name: hematrack
version: 0.1.0+1
description: MVP aplikasi monitoring visual hemangioma anak dengan baseline photo dan ghost overlay.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0
  image: ^4.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.2.2
  fl_chart: ^0.69.0
  pdf: ^3.11.1
  printing: ^5.13.2
  uuid: ^4.5.1
  intl: ^0.19.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
